name: testlab

# Servicios a desplegar
services: 

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: ${NAME}-wiremock
    volumes:
      - ./docker/wiremock:/home/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 9561:8080