name: testlab

# Servicios a desplegar
services: 

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: ${NAME}-wiremock
    volumes:
      - ./docker/wiremock:/home/wiremock
    command: [
        "--global-response-templating",
        "--disable-gzip",
        "--verbose",
        "--print-all-network-traffic"
      ]
    ports:
      - 9561:8080