name: testlab

# Servicios a desplegar
services: 

  wiremock:
    image: wiremock/wiremock:latest
    volume: ./docker/wiremock:/home/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports: 9156:8080